server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: edumaster-pro
    
  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/edumaster_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: none  # Use Flyway for schema management
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    defer-datasource-initialization: false
    
  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    
  # Mail Configuration
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      
# JWT Configuration
jwt:
  secret: ${JWT_SECRET:myVerySecureSecretKeyThatIsSufficientlyLongForHMACAlgorithms123456789}
  expiration: 86400000  # 24 hours in milliseconds
  refresh-expiration: 604800000  # 7 days in milliseconds
  
# Stripe Configuration
stripe:
  public-key: ${STRIPE_PUBLIC_KEY:pk_test_your_public_key}
  secret-key: ${STRIPE_SECRET_KEY:sk_test_your_secret_key}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_your_webhook_secret}
  
# Application Configuration
app:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
  file-upload-path: ${FILE_UPLOAD_PATH:./uploads}
  max-file-size: 50MB
  
# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
      
# Logging Configuration
logging:
  level:
    com.edumaster: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/edumaster.log